// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WpfApp1.Contexts;

#nullable disable

namespace WpfApp1.Migrations
{
    [DbContext(typeof(WorkshopDbContext))]
    partial class WorkshopDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("WpfApp1.Models.ClientVehicles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Car_Model")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Car_RegNo")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Car_Vin")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Car_Year")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Client_Id")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("Client_Id");

                    b.ToTable("Client_Vehicles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Car_Model = "Seat Ibiza 3",
                            Car_RegNo = "KWI9123",
                            Car_Vin = "3VWSB81H8WM210368",
                            Car_Year = 2003,
                            Client_Id = 1
                        },
                        new
                        {
                            Id = 2,
                            Car_Model = "Dodge Ram Pickup",
                            Car_RegNo = "KRTEST",
                            Car_Vin = "1D7HA16D94J171206",
                            Car_Year = 2016,
                            Client_Id = 2
                        });
                });

            modelBuilder.Entity("WpfApp1.Models.Clients", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Building_No")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Phonenumber")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Postalcode")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Clients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Building_No = "12a",
                            City = "Wieliczka",
                            Firstname = "Denis",
                            Lastname = "Biskup",
                            Phonenumber = "123456789",
                            Postalcode = "32-020",
                            Street = "Fajna"
                        },
                        new
                        {
                            Id = 2,
                            Building_No = "1",
                            City = "Testowe",
                            Firstname = "Test",
                            Lastname = "Tester",
                            Phonenumber = "111222333",
                            Postalcode = "12-011",
                            Street = "Testowa"
                        });
                });

            modelBuilder.Entity("WpfApp1.Models.EmployeeTitles", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Hourly_Paycheck")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Employee_Titles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Hourly_Paycheck = 25,
                            Name = "Novice"
                        },
                        new
                        {
                            Id = 2,
                            Hourly_Paycheck = 35,
                            Name = "Mechanic"
                        },
                        new
                        {
                            Id = 3,
                            Hourly_Paycheck = 50,
                            Name = "Manager"
                        });
                });

            modelBuilder.Entity("WpfApp1.Models.Users", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<int>("Employee_Title_Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Employee_Title_Id");

                    b.ToTable("Users");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Employee_Title_Id = 3,
                            Name = "admin",
                            Password = "$2a$11$5Q4XJlPQM2r2rwk9qMJdp.yT0IYabz6SPq5gpPHggLQkcNTk5Gs6i"
                        });
                });

            modelBuilder.Entity("WpfApp1.Models.ClientVehicles", b =>
                {
                    b.HasOne("WpfApp1.Models.Clients", "Client")
                        .WithMany("Vehicles")
                        .HasForeignKey("Client_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("WpfApp1.Models.Users", b =>
                {
                    b.HasOne("WpfApp1.Models.EmployeeTitles", "EmployeeTitle")
                        .WithMany("Users")
                        .HasForeignKey("Employee_Title_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("EmployeeTitle");
                });

            modelBuilder.Entity("WpfApp1.Models.Clients", b =>
                {
                    b.Navigation("Vehicles");
                });

            modelBuilder.Entity("WpfApp1.Models.EmployeeTitles", b =>
                {
                    b.Navigation("Users");
                });
#pragma warning restore 612, 618
        }
    }
}
